# Generated by Django 2.1.3 on 2018-11-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181130_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', '管理员'), ('User', '普通用户')], default='User', max_length=10, verbose_name='Role'),
        ),
    ]
