# Generated by Django 2.1.3 on 2018-11-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181130_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='created_by',
            field=models.CharField(blank=True, max_length=30, verbose_name='Created by'),
        ),
    ]
