# Generated by Django 2.1.3 on 2018-12-02 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20181130_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_superuser',
        ),
    ]
