# Generated by Django 2.1.3 on 2018-12-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_myuser_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', '管理员'), ('User', '普通用户'), ('App', '应用程序')], default='User', max_length=10, verbose_name='Role'),
        ),
    ]
