# Generated by Django 2.1.3 on 2018-12-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20181202_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='name',
            field=models.CharField(max_length=128, null=True, verbose_name='Name'),
        ),
    ]
