# Generated by Django 2.1.3 on 2018-12-03 12:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('even_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=70)),
                ('created_time', models.DateTimeField()),
                ('modified_time', models.DateTimeField()),
                ('system_name', models.CharField(max_length=128, null=True, verbose_name='System Name')),
                ('even_level', models.CharField(blank=True, choices=[('level_1', '1级事件'), ('level_2', '2级事件'), ('level_3', '3级事件'), ('level_4', '4级事件'), ('level_5', '5级事件'), ('level_6', '6级事件'), ('level_7', '7级事件')], default='LEVEL_7', max_length=10, verbose_name='Even Level')),
                ('even_ops', models.CharField(blank=True, max_length=20, null=True, verbose_name='Even Ops')),
                ('even_dev', models.CharField(blank=True, max_length=20, null=True, verbose_name='Even Dev')),
                ('comment', models.TextField(blank=True, max_length=200, verbose_name='Even Comment')),
                ('even_state', models.CharField(blank=True, choices=[('state_1', '待审批'), ('state_2', '已审批'), ('state_3', '已处理'), ('state_4', '关闭')], default='LEVEL_7', max_length=10, verbose_name='Even Level')),
            ],
        ),
    ]
