# Generated by Django 2.1.3 on 2018-12-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='even_state',
            field=models.CharField(blank=True, choices=[('state_1', '待审批'), ('state_2', '已审批'), ('state_3', '已处理'), ('state_4', '关闭')], default='LEVEL_7', max_length=10, verbose_name='Even State'),
        ),
    ]
