# Generated by Django 2.1.3 on 2018-12-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20181203_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_time',
            field=models.DateTimeField(verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='event',
            name='even_level',
            field=models.CharField(blank=True, choices=[('level_1', '1级事件'), ('level_2', '2级事件'), ('level_3', '3级事件'), ('level_4', '4级事件'), ('level_5', '5级事件'), ('level_6', '6级事件'), ('level_7', '7级事件')], default='LEVEL_7', max_length=10, verbose_name='事件等级'),
        ),
        migrations.AlterField(
            model_name='event',
            name='modified_time',
            field=models.DateTimeField(verbose_name='修改时间'),
        ),
    ]
